### ISSUE TITLE
 Quotes not displaying in profile README 

### ISSUE THREAD

**Issue by imHardik1606** [PiyushSuthar/github-readme-quotes#45]
### **Description:**
I am facing an issue where quotes are not displaying in my profile README. I have tried the following steps to resolve it, but the problem persists:  

1. Checked the internet connection.  
2. Tried accessing the README from different browsers (Chrome, Firefox, Brave).  
3. Refreshed the GitHub cache by updating the README.  

Unfortunately, none of these actions resolved the issue. The quotes section appears blank in the README.  

### **Expected Behavior:**  
The quotes should display correctly in the profile README.  

### **Actual Behavior:**  
![Screenshot 2024-11-25 193128](https://github.com/user-attachments/assets/e20dfaf5-b7df-4d2d-bb08-da323b2a802c)
It's just displaying a link

### **Environment:**  
- Operating System: [Windows 11]  
- Browser: [Chrome 118, Brave 118]  

Please let me know if additional details or steps are needed to resolve this issue.

**Comment by ZRJohnson208** [comment]
I went to the link (``https://quotes-github-readme.vercel.app/api?type=horizontal&theme=dark``). This is what I found:
![image](https://github.com/user-attachments/assets/4f08d4e5-afc6-4938-99ee-b57e5abc5788)
Error 500, according to Vercel.app doc is an error  that "occurs when a function invocation fails. This could be due to an error within the function itself, or an issue with the environment in which the function is running."

**Comment by imHardik1606** [comment]
The Error 500 (FUNCTION_INVOCATION_FAILED) typically indicates an internal issue in the backend function or its hosting environment. I don't know should we tag owner of this repo ?

**Comment by ZRJohnson208** [comment]
Yeah, that may be the best step foreword. I have the doc link here: https://vercel.com/docs/errors/FUNCTION_INVOCATION_FAILED

**Comment by U-L-M-S** [comment]
The problem occurred because the repository containing all the quotes was deleted (https://github.com/skolakoda/programming-quotes-api/raw/master/Data/quotes.json). 

To resolve it, a new `quoteDB` needs to be set in [[this line](https://github.com/PiyushSuthar/github-readme-quotes/blob/b168e7dda85818d243ac5caf33b302291073ee9c/src/fetcher/fetch-quotes.ts#L34)](https://github.com/PiyushSuthar/github-readme-quotes/blob/b168e7dda85818d243ac5caf33b302291073ee9c/src/fetcher/fetch-quotes.ts#L34).

**Comment by ZRJohnson208** [comment]
Alright, good to know. It seems they deleted the ``raw`` directory file entirely.  

I found it again here: https://github.com/mudroljub/programming-quotes-api/blob/master/data/quotes.json

I or one of us will make a PR to fix this issue. Thanks.

**Comment by U-L-M-S** [comment]
@PiyushSuthar I created a PR and it should solve the problem.
For some reason I tested and once I make the request via browser (https://github-readme-quotes-5tf1nvez2-ulms-projects.vercel.app/api?theme=radical&type=horizontal) it simple works but as soon I insert it on my README it doesn't show the img. 
Can you give me a hit what I should do ? or what is the problem ?

**Comment by U-L-M-S** [comment]
UPDATE:
It works!
The reason for NOT working before was because of a TYPO

```
[![Readme Quotes](https://quotes.uinclis.de/api?type=horizontal&theme=dark)](https://github.com/U-L-M-S/github-readme-quotes)
```
OR
```
<div align=center>
<img width=700 src='[https://quotes.uinclis.de/api?type=horizontal&theme=radical'/>](https://https//quotes.uinclis.de/api?type=horizontal&theme=radical%27/%3E)
</div>
```

You can use it as an TEMP solution :)

**Comment by PiyushSuthar** [comment]
Thank you all for reporting the issue and submitting the PR. I’ve been occupied with exams recently and hadn’t had a chance to check GitHub.
